# IDX Data Analyst Internship

### Week 1- downloading the files, setting up python, setting up git, cleaning data.

In [10]:
#Imports
import pandas as pd
import crmls_listed
import crmls_sold

Total 31888 records exported to CRMLSListing202602.csv
Total 19086 records exported to CRMLSSold202602.csv

In [11]:
df_listings= pd.read_csv("CRMLSListing202602.csv")
df_sold = pd.read_csv("CRMLSSold202602.csv")

### Displaying the data frames

In [12]:
df_sold

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName
0,HighDesert,HighDesert,NaN,False,NaN,NaN,False,1850000.0,1156290692,2026-02-26,...,NaN,False,20.0,NaN,92307,0.0,29698.0,NaN,CRMLS,CRMLS_CRM
1,ContraCosta,BayEast,NaN,NaN,NaN,NaN,NaN,1580000.0,1155696412,2026-02-19,...,NaN,NaN,NaN,NaN,95821,0.0,18682.0,NaN,CRMLS,CRMLS_CCBE
2,OrangeCounty,OrangeCounty,"Carpet,Tile",False,NaN,NaN,False,1100000.0,1155620121,2026-02-27,...,3.0,False,2.0,Irvine Unified,92604,NaN,5000.0,NaN,CRMLS,CRMLS_CRM
3,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,NaN,NaN,False,999000.0,1155350576,2026-02-27,...,NaN,False,NaN,NaN,91411,NaN,12005.0,NaN,CRMLS,CRMLS_CL
4,SanDiego,SanDiego,NaN,NaN,NaN,NaN,NaN,1650000.0,1155221012,2026-02-14,...,NaN,NaN,NaN,NaN,91910,0.0,6851.0,NaN,CRMLS,CRMLS_SAND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19081,CaliforniaDesert,CaliforniaDesert,"Carpet,Tile",True,NaN,NaN,True,11500.0,1020380240,2026-02-01,...,NaN,False,2.0,NaN,92270,350.0,13504.0,NaN,CRMLS,CRMLS_CDAR
19082,JoshuaTreeGateway,JoshuaTreeGateway,NaN,True,NaN,NaN,NaN,250000.0,1019908389,2026-02-13,...,NaN,False,NaN,NaN,92252,0.0,328878.0,NaN,CRMLS,CRMLS_CRM
19083,Southland,Southland,NaN,True,NaN,NaN,NaN,49999.0,541645473,2026-02-25,...,NaN,False,NaN,NaN,93534,0.0,104024.0,NaN,CRMLS,CRMLS_CRM
19084,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,299900.0,532189426,2026-02-27,...,NaN,False,NaN,NaN,92506,0.0,60113.0,NaN,CRMLS,CRMLS_CRM
19085,OrangeCounty,TriCounties,NaN,False,NaN,NaN,NaN,900000.0,425835813,2026-02-10,...,NaN,False,NaN,NaN,91709,0.0,82800.0,NaN,CRMLS,CRMLS_CRM

In [13]:
df_listings

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,595000.0,1156501420,2026-03-27,595000.0,SCOTT,GEE,34.125786,-117.530546,7065 Marigold Court,Residential,...,3.0,False,2.0,Chaffey Joint Union High,91739,REALTY MASTERS & ASSOCIATES,0.0,3500.0,NaN,7065 Marigold Court
1,1450000.0,1156498573,NaN,NaN,Grace,Miranda,34.141080,-118.260394,357 Vine Street,Residential,...,1.0,False,3.0,Glendale Unified,91204,NaN,0.0,6258.0,NaN,357 Vine Street
2,2199888.0,1156498166,NaN,NaN,Martha,Haecherl,33.908148,-117.864165,3023 Limewood Court,Residential,...,1.0,False,3.0,Placentia-Yorba Linda Unified,92835,NaN,346.0,10223.0,NaN,3023 Limewood Court
3,1300000.0,1156495523,NaN,NaN,Mike,Chou,34.106584,-118.063318,9511 Las Tunas,CommercialSale,...,NaN,NaN,NaN,NaN,91780,NaN,NaN,4825.0,NaN,9511 Las Tunas
4,1925000.0,1156494957,NaN,NaN,Margaret,Van Herk,33.675282,-117.980216,8482 Deepview Drive,Residential,...,1.0,False,2.5,Huntington Beach Union High,92646,NaN,0.0,6580.0,NaN,8482 Deepview Drive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31883,4950.0,1149458718,NaN,NaN,Alphonso,Lascano,34.044402,-118.365074,1716 S Genesee Avenue,ResidentialLease,...,NaN,False,NaN,NaN,90019,NaN,NaN,4886.0,NaN,1716 S Genesee Avenue
31884,1699.0,1146439434,NaN,NaN,Gene,Smith,38.115612,-122.267146,124 Benson Ave,ResidentialLease,...,NaN,False,1.0,NaN,94590,NaN,NaN,15681.0,NaN,124 Benson Ave
31885,350000.0,1146104836,NaN,NaN,Jason,Lipovsky,33.139128,-117.053881,475 N Midway Drive 169,Residential,...,0.0,NaN,0.0,Escondido Union,92027,NaN,400.0,261360.0,NaN,475 N Midway Drive 169
31886,1325.0,1107246684,NaN,NaN,Kathy,Lund,32.572312,-117.034778,4589 Casa nova ct,ResidentialLease,...,5.0,False,2.0,Other,92154,NaN,0.0,2224.0,NaN,4589 Casa nova ct
31887,6000.0,1063377179,NaN,NaN,Jaime,Rook,33.162293,-117.266434,4717 Majorca Way,ResidentialLease,...,NaN,NaN,2.0,Oceanside Unified,92056,NaN,NaN,3519.0,NaN,4717 Majorca Way