# IDX Data Analyst Internship

### Week 1- downloading the files, setting up python, setting up git, cleaning data.

In [17]:
#Imports
import pandas as pd
import crmls_listed
import crmls_sold

In [18]:
import glob

In [19]:
df_listings= pd.read_csv("CRMLSListing202602.csv")
df_sold = pd.read_csv("CRMLSSold202602.csv")

### Displaying the data frames

In [23]:
glob.glob("*.csv")

['CRMLSListing202602.csv', 'CRMLSSold202602.csv']

In [24]:
len(glob.glob("CRMLSSold*.csv"))

1

In [25]:
sold_files = glob.glob("CRMLSSold*.csv")
listed_files = glob.glob("CRMLSListing*.csv")

print(len(sold_files))
print(len(listed_files))

1
1

In [27]:
import os
os.listdir()

['.DS_Store',
 'crmls_sold.py',
 'CRMLSListing202602.csv',
 '__pycache__',
 'README.md',
 '.gitignore',
 'CRMLSSold202602.csv',
 '.git',
 'crmls_listed.py',
 'analysis.ipynb',
 'raw']

In [30]:
sold_files = glob.glob("raw/CRMLSSold*.csv")
df_sold = pd.concat([pd.read_csv(f, low_memory= False) for f in sold_files], ignore_index=True)

In [29]:
df_listings = pd.concat(
    [pd.read_csv(f, low_memory=False) for f in listed_files],
    ignore_index=True)

In [62]:
# Looking at the original data set 
df_sold

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation
0,Arcadia,Arcadia,NaN,False,NaN,NaN,False,1130000.0,538338723,espi.bagwell@kw.com,...,91016,0.0,14390.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Conejo,Conejo,NaN,True,NaN,NaN,NaN,1795000.0,535502637,david@mabryflp.com,...,93021,NaN,666032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,99000.0,495549184,Jaredengberg@rocketmail.com,...,92283,0.0,871200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,40000.0,446937009,Julie@whitehornhomes.com,...,92530,0.0,16553.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HighDesert,HighDesert,NaN,True,NaN,NaN,NaN,59900.0,446912267,nadinesells4u@gmail.com,...,92327,0.0,275800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,649000.0,1008475397,chiggamasta424@gmail.com,...,90805,NaN,4682.0,NaN,NaN,NaN,NaN,NaN,Item1,2.5
532591,NaN,NaN,NaN,True,NaN,NaN,NaN,75689.0,1003434877,jhisquierdo@lee-associates.com,...,92371,NaN,946123.0,NaN,NaN,NaN,NaN,NaN,Item1,4.0
532592,NaN,NaN,NaN,True,NaN,NaN,NaN,275000.0,1002713752,MLS@DaltonRealtors.com,...,92082,0.0,619859.0,NaN,NaN,NaN,NaN,NaN,Item1,2.0
532593,NaN,NaN,NaN,False,NaN,NaN,False,10000.0,1002447928,Tazzie@CoronadoPremierProperties.com,...,92118,0.0,NaN,NaN,NaN,NaN,NaN,NaN,Item,100.0
532594,NaN,NaN,NaN,True,NaN,NaN,NaN,1600000.0,1001660596,diana@countryqueen.com,...,91765,294.0,52212.0,NaN,NaN,NaN,NaN,NaN,Item1,2.0

In [63]:
#Looking at the original data set
df_listings

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,595000.0,1156501420,2026-03-27,595000.0,SCOTT,GEE,34.125786,-117.530546,7065 Marigold Court,Residential,...,3.0,False,2.0,Chaffey Joint Union High,91739,REALTY MASTERS & ASSOCIATES,0.0,3500.0,NaN,7065 Marigold Court
1,1450000.0,1156498573,NaN,NaN,Grace,Miranda,34.141080,-118.260394,357 Vine Street,Residential,...,1.0,False,3.0,Glendale Unified,91204,NaN,0.0,6258.0,NaN,357 Vine Street
2,2199888.0,1156498166,NaN,NaN,Martha,Haecherl,33.908148,-117.864165,3023 Limewood Court,Residential,...,1.0,False,3.0,Placentia-Yorba Linda Unified,92835,NaN,346.0,10223.0,NaN,3023 Limewood Court
3,1300000.0,1156495523,NaN,NaN,Mike,Chou,34.106584,-118.063318,9511 Las Tunas,CommercialSale,...,NaN,NaN,NaN,NaN,91780,NaN,NaN,4825.0,NaN,9511 Las Tunas
4,1925000.0,1156494957,NaN,NaN,Margaret,Van Herk,33.675282,-117.980216,8482 Deepview Drive,Residential,...,1.0,False,2.5,Huntington Beach Union High,92646,NaN,0.0,6580.0,NaN,8482 Deepview Drive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31883,4950.0,1149458718,NaN,NaN,Alphonso,Lascano,34.044402,-118.365074,1716 S Genesee Avenue,ResidentialLease,...,NaN,False,NaN,NaN,90019,NaN,NaN,4886.0,NaN,1716 S Genesee Avenue
31884,1699.0,1146439434,NaN,NaN,Gene,Smith,38.115612,-122.267146,124 Benson Ave,ResidentialLease,...,NaN,False,1.0,NaN,94590,NaN,NaN,15681.0,NaN,124 Benson Ave
31885,350000.0,1146104836,NaN,NaN,Jason,Lipovsky,33.139128,-117.053881,475 N Midway Drive 169,Residential,...,0.0,NaN,0.0,Escondido Union,92027,NaN,400.0,261360.0,NaN,475 N Midway Drive 169
31886,1325.0,1107246684,NaN,NaN,Kathy,Lund,32.572312,-117.034778,4589 Casa nova ct,ResidentialLease,...,5.0,False,2.0,Other,92154,NaN,0.0,2224.0,NaN,4589 Casa nova ct
31887,6000.0,1063377179,NaN,NaN,Jaime,Rook,33.162293,-117.266434,4717 Majorca Way,ResidentialLease,...,NaN,NaN,2.0,Oceanside Unified,92056,NaN,NaN,3519.0,NaN,4717 Majorca Way

In [ ]:
#Displaying column names to filter data and create new data frames.
df_sold.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'latfilled', 'lonfilled', 'OriginatingSystemName',
       'OriginatingSystemSubName', 'BuyerAgencyCompensationType',
       'BuyerAgencyCompensation'],
      dtype='object')

In [61]:
df_listings.columns

Index(['OriginalListPrice', 'ListingKey', 'CloseDate', 'ClosePrice',
       'ListAgentFirstName', 'ListAgentLastName', 'Latitude', 'Longitude',
       'UnparsedAddress', 'PropertyType', 'LivingArea', 'ListPrice',
       'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'PropertyType.1', 'MlsStatus', 'ElementarySchool',
       'ListAgentFirstName.1', 'AttachedGarageYN', 'ParkingTotal',
       'BuilderName', 'PropertySubType', 'LotSizeAcres', 'SubdivisionName',
       'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1', 'StreetNumberNumeric',
       'LivingArea.1', 'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'Longitude.1', 'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'Latitude.1', 'ListPrice.1', 'StateOrProvince',
       'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories',
       'HighSchool', 'Levels', 'ListAgentLastName.1', 'CloseDate.1',
       'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1'],
      dtype='object')

### Creatign new data frames with our variables of interest:

#### Key MLS Fields

List Price / Close Price — Transaction pricing data

Square Footage — Property size metrics

(LivingArea)
Bedrooms / Bathrooms — Property configuration

Property Type — Residential, Condo, etc.

Listing Agent / Brokerage — Agent and firm attribution

Days on Market (DaysOnMarket) — Time-to-sell metric

In [44]:
df_sold_new = df_sold[["ClosePrice","ListPrice", "LotSizeSquareFeet","BedroomsTotal", "BathroomsTotalInteger","PropertyType", "BuyerAgentAOR", "ListAgentAOR", "DaysOnMarket"]].copy()
df_sold_new

,ClosePrice,ListPrice,LotSizeSquareFeet,BedroomsTotal,BathroomsTotalInteger,PropertyType,BuyerAgentAOR,ListAgentAOR,DaysOnMarket
0,1090000.0,1130000.0,14390.0,3.0,4.0,Residential,Arcadia,Arcadia,26
1,1000000.0,1200000.0,666032.0,NaN,0.0,Land,Conejo,Conejo,1134
2,12999.0,14999.0,871200.0,NaN,NaN,Land,OrangeCounty,OrangeCounty,1108
3,40000.0,40000.0,16553.0,NaN,NaN,Land,SouthwestRiversideCounty,SouthwestRiversideCounty,1517
4,69000.0,79900.0,275800.0,NaN,NaN,Land,HighDesert,HighDesert,1476
...,...,...,...,...,...,...,...,...,...
532590,450000.0,549000.0,4682.0,NaN,NaN,CommercialSale,NaN,NaN,769
532591,75689.0,75689.0,946123.0,NaN,NaN,Land,NaN,NaN,547
532592,100000.0,99000.0,619859.0,NaN,NaN,Land,NaN,NaN,846
532593,8300.0,8300.0,NaN,3.0,4.0,ResidentialLease,NaN,NaN,58
532594,1050000.0,1250000.0,52212.0,NaN,NaN,Land,NaN,NaN,826

In [53]:
df_listing_new= df_listings[["ListPrice","ClosePrice", "LotSizeSquareFeet","LivingArea", "BedroomsTotal", "BathroomsTotalInteger","PropertyType", "DaysOnMarket", "ListAgentFirstName","ListAgentLastName", "ListAgentFullName","ListOfficeName","CoListOfficeName"]].copy()
df_listing_new

,ListPrice,ClosePrice,LotSizeSquareFeet,LivingArea,BedroomsTotal,BathroomsTotalInteger,PropertyType,DaysOnMarket,ListAgentFirstName,ListAgentLastName,ListAgentFullName,ListOfficeName,CoListOfficeName
0,595000.0,595000.0,3500.0,949.0,3.0,2.0,Residential,0,SCOTT,GEE,SCOTT GEE,REALTY MASTERS & ASSOCIATES,NaN
1,1450000.0,NaN,6258.0,2010.0,3.0,3.0,Residential,0,Grace,Miranda,Grace Miranda,Keller Williams Realty World Media Center,NaN
2,2199888.0,NaN,10223.0,3654.0,4.0,3.0,Residential,0,Martha,Haecherl,Martha Haecherl,Keller Williams Realty,NaN
3,1300000.0,NaN,4825.0,NaN,NaN,NaN,CommercialSale,0,Mike,Chou,Mike Chou,K.W. EXECUTIVE,NaN
4,1925000.0,NaN,6580.0,2273.0,4.0,3.0,Residential,0,Margaret,Van Herk,Margaret Van Herk,Seven Gables Real Estate,Seven Gables Real Estate
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31883,4950.0,NaN,4886.0,1008.0,2.0,2.0,ResidentialLease,15,Alphonso,Lascano,Alphonso Lascano,Carolwood Estates,Carolwood Estates
31884,1650.0,NaN,15681.0,7920.0,2.0,1.0,ResidentialLease,42,Gene,Smith,Gene Smith,First Republic Real Estate,NaN
31885,335000.0,NaN,261360.0,1032.0,2.0,1.0,Residential,76,Jason,Lipovsky,Jason Lipovsky,Venture Pacific Properties,NaN
31886,1149.0,NaN,2224.0,2224.0,1.0,1.0,ResidentialLease,359,Kathy,Lund,Kathy Lund,Integrity First Realty & Loans,Integrity First Realty & Loans
31887,6300.0,NaN,3519.0,1444.0,2.0,2.0,ResidentialLease,710,Jaime,Rook,Jaime Rook,JMR Real Estate,NaN

In [55]:
df_listing_new.describe()

,ListPrice,ClosePrice,LotSizeSquareFeet,LivingArea,BedroomsTotal,BathroomsTotalInteger,DaysOnMarket
count,3.179800e+04,8.551000e+03,2.916100e+04,27580.000000,27696.000000,28986.000000,31888.000000
mean,1.027134e+06,8.044481e+05,3.871424e+05,1937.415319,3.153668,2.534534,19.900151
std,2.185343e+06,1.149745e+06,1.593119e+07,1621.207150,2.033463,2.023989,17.995362
min,1.000000e+00,1.770000e+00,0.000000e+00,0.000000,0.000000,0.000000,-10.000000
25%,1.349992e+05,4.700000e+03,5.300000e+03,1175.000000,2.000000,2.000000,6.000000
50%,6.490000e+05,6.000000e+05,7.633000e+03,1605.000000,3.000000,2.000000,16.000000
75%,1.188964e+06,1.150000e+06,1.846800e+04,2263.000000,4.000000,3.000000,32.000000
max,9.135000e+07,3.026000e+07,1.897866e+09,94619.000000,149.000000,149.000000,710.000000

In [56]:
df_sold_new.describe()

,ClosePrice,ListPrice,LotSizeSquareFeet,BedroomsTotal,BathroomsTotalInteger,DaysOnMarket
count,5.325900e+05,5.317780e+05,4.830150e+05,497152.000000,507915.000000,532595.00000
mean,8.800521e+05,8.437559e+05,4.523878e+05,3.082136,2.445110,42.33038
std,5.378529e+06,1.275921e+06,1.925662e+07,1.388929,1.413445,69.37806
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,-288.00000
25%,6.500000e+04,7.500000e+04,5.175000e+03,2.000000,2.000000,8.00000
50%,6.339885e+05,6.350000e+05,7.276000e+03,3.000000,2.000000,21.00000
75%,1.075000e+06,1.070000e+06,1.276800e+04,4.000000,3.000000,52.00000
max,9.895000e+08,1.375000e+08,2.208318e+09,123.000000,175.000000,12430.00000

In [59]:
df_listing_new.head()

,ListPrice,ClosePrice,LotSizeSquareFeet,LivingArea,BedroomsTotal,BathroomsTotalInteger,PropertyType,DaysOnMarket,ListAgentFirstName,ListAgentLastName,ListAgentFullName,ListOfficeName,CoListOfficeName
0,595000.0,595000.0,3500.0,949.0,3.0,2.0,Residential,0,SCOTT,GEE,SCOTT GEE,REALTY MASTERS & ASSOCIATES,NaN
1,1450000.0,NaN,6258.0,2010.0,3.0,3.0,Residential,0,Grace,Miranda,Grace Miranda,Keller Williams Realty World Media Center,NaN
2,2199888.0,NaN,10223.0,3654.0,4.0,3.0,Residential,0,Martha,Haecherl,Martha Haecherl,Keller Williams Realty,NaN
3,1300000.0,NaN,4825.0,NaN,NaN,NaN,CommercialSale,0,Mike,Chou,Mike Chou,K.W. EXECUTIVE,NaN
4,1925000.0,NaN,6580.0,2273.0,4.0,3.0,Residential,0,Margaret,Van Herk,Margaret Van Herk,Seven Gables Real Estate,Seven Gables Real Estate

In [58]:
df_sold_new.head()

,ClosePrice,ListPrice,LotSizeSquareFeet,BedroomsTotal,BathroomsTotalInteger,PropertyType,BuyerAgentAOR,ListAgentAOR,DaysOnMarket
0,1090000.0,1130000.0,14390.0,3.0,4.0,Residential,Arcadia,Arcadia,26
1,1000000.0,1200000.0,666032.0,NaN,0.0,Land,Conejo,Conejo,1134
2,12999.0,14999.0,871200.0,NaN,NaN,Land,OrangeCounty,OrangeCounty,1108
3,40000.0,40000.0,16553.0,NaN,NaN,Land,SouthwestRiversideCounty,SouthwestRiversideCounty,1517
4,69000.0,79900.0,275800.0,NaN,NaN,Land,HighDesert,HighDesert,1476

### Cleaning the data 
##### 1) Looking at the missing values, which to remove and which to keep.
##### 2) changing any quatitative variable with letters inside.

git add .
git commit -m "your message"
git pull origin main --rebase
git push origin main